### ISSUE TITLE
handleas option in request

### ISSUE THREAD

**Issue by ghost** [dojo/core#106]
this option seems to be no used in request(xhr), instead, i found the option responseType when i need a json parsing

**Comment by kitsonk** [comment]
I suspect we should add [`handleAs` to the `json` filter](https://github.com/dojo/core/blob/be09f0e0116f9af57414679147580110cbee3b54/src/request.ts#L198).  Thoughts @bryanforbes?

**Comment by taoqf** [comment]
i do agree, too.
