### ISSUE TITLE
FIDO 2.0

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#140]
Investigate of the impact/desire to integrate FIDO 2.0 APIs which are starting to be delivered in browsers.

**Comment by dylans** [comment]
https://www.w3.org/Submission/2015/SUBM-fido-web-api-20151120/

**Comment by kitsonk** [comment]
At this time we don't have a strong use case... After we deliver the "application" login and authentication might very well be other features we start to tackle, but we want to do it in a holistic approach.  Closing...
