### ISSUE TITLE
Integrate Iterators

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#143]
Now that we have a shim for Iterators landed in master, we should integrate them better across core.  Areas that I can think of:
- [ ] Handling `dojo/array::from`.
- [ ] Convert `dojo/Map` to a proper shim, which offloads to native and exposes iterator interfaces
- [ ] `Promise.all` and `Promise.race` should work with iterators
- [ ] See if `dojo/async/iteration` can benefit from exposing iterator interfaces

There maybe more I am not thinking of.

**Comment by mwistrand** [comment]
Since the `ArrayLike` interface is not compatible with the ES2015 `Map` constructor signature, converting `src/Map` to a proper shim will result in a change in functionality. I am proceeding with the assumption that we are okay with that, and have made a note to spot-check any usage of the current implementation across the various Dojo 2 repos.

**Comment by mwistrand** [comment]
`Promise.all` and `Promise.race` both accept iterators, so I'm in the process of updating those as well.

**Comment by kitsonk** [comment]
> I am proceeding with the assumption that we are okay with that, and have made a note to spot-check any usage of the current implementation across the various Dojo 2 repos.

I can only think that I might have used `Map` in `dojo/widgets`, but I don't think I would have used the `Map([])` as a constructor (since the use case of converting an `ArrayLike` to a `Map` is a bit limited).

**Comment by mwistrand** [comment]
@kitsonk Do you have any preference for handle limited support in environments with limited `Map` support? For example, Safari/IE do not support an argument to the constructor, and IE does not support `key`, `values`, or `entries`.

**Comment by kitsonk** [comment]
I would say we provide the shim being full ES6 compatibility and use the shim for any native implementations that aren't ES6 complaint (so the has feature should check for ES6 compatibility).
