### ISSUE TITLE
Merge compose/aspect.ts and core/aspect.ts

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#144]
We should rationalise [compose/aspect](https://github.com/dojo/compose/blob/master/src/aspect.ts) and core/aspect.

Relates to #61 in what is the API of core/aspect.

**Comment by kitsonk** [comment]
We seem to be surviving on this fine... need to do one day though, but not a beta blocker.

**Comment by dylans** [comment]
For API sanity, it's probably worth cleaning this up for beta?
