### ISSUE TITLE
interface 'Symbol' is not exported

### ISSUE THREAD

**Issue by taoqf** [dojo/core#148]
```
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(912,11): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(913,11): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(956,7): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(959,7): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(973,7): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(1020,11): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(1021,11): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(1035,7): error TS2304: Cannot find name 'Symbol'.
typings/dojo-core/dojo-core-2.0.0-pre.d.ts(1036,7): error TS2304: Cannot find name 'Symbol'.
```

**Comment by taoqf** [comment]
this occurse when target is es5
`"target": "es5",`

`"target": "es6",`is ok

**Comment by kitsonk** [comment]
Because the `Symbol` can conflict with other declarations (like when targeting ES6) when consuming `core` while targeting `es5` you need to have the [typings/symbol-shim.d.ts](https://github.com/dojo/core/blob/master/typings/symbol-shim/symbol-shim.d.ts) included in your project as well as the [typings/dojo-core/dojo-core-2.0.0-pre.d.ts].  Eventually we will figure out a better way to do this or properly document it.

**Comment by taoqf** [comment]
when i upgrade dojo-core to alpha7, i find the file symbol-shim.d.ts is missing.
and i got the same error, again. what should i do? help me please @kitsonk

**Comment by taoqf** [comment]
luckly, i have found the symbol-shim.d.ts and added to my typings

**Comment by kitsonk** [comment]
@taoqf yes, sorry... we migrated to [typings/typings](https://github.com/typings/typings).  We are now maintain this (and other typings) at [dojo/typings](https://github.com/dojo/typings).

The file is located here: [symbol-shim.d.ts](https://github.com/dojo/typings/blob/master/custom/symbol-shim/symbol-shim.d.ts) and you can also have this managed by "typings/typings" by adding the following entry to your `typings.json`:

``` json
{
  "globalDevDependencies": {
    "symbol-shim": "github:dojo/typings/custom/symbol-shim/symbol-shim.d.ts#9a0185f465a3febe2bb1ff3f1210f43e5f96c5d2"
  }
}
```

**Comment by kitsonk** [comment]
Also, note that in TypeScript 2, we should be able to declare the `Symbol` interface in `dojo-core` and not have have a conflict (see [Microsoft/TypeScript#8696](https://github.com/Microsoft/TypeScript/pull/8696)).

**Comment by taoqf** [comment]
thanks
