### ISSUE TITLE
Bad Symbol string compared to native symbols

### ISSUE THREAD

**Issue by novemberborn** [dojo/core#170]
The Node.js REPL (v6) gives:

```
> Symbol('foo').toString()
'Symbol(foo)'
```

However, in a v0.10 REPL, `dojo-core/Symbol` gives:

```
> require('dojo-core').Symbol('foo').toString()
'@@foo'
```

**Comment by kitsonk** [comment]
This is one of the features of `Symbol` that cannot be polyfilled.

[Kangax](https://kangax.github.io/compat-table/es6/#test-Symbol_can_convert_with_String%28%29) notes that all polyfills suffer from a `.toString()` and a coercion problems.

What functionality is this breaking/impacts it is causing?

**Comment by novemberborn** [comment]
> What functionality is this breaking/impacts it is causing?

See https://github.com/dojo/app/pull/3/commits/25ab6c5bad4d207379d21f8641cd77a7c40be5d2.

**Comment by novemberborn** [comment]
Wontfix then.
