### ISSUE TITLE
Negative Index causing issues on FF 33 and 34

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#175]
The test to detect handling of [negative object indexes](https://github.com/dojo/core/blob/a4e2f7e720250ae1b14f36407eb99ead1452d59b/tests/unit/array.ts#L110) is blowing up FF 33 and 34 according to @jason0x43.  This causes the browser to become unresponsive and therefore hands the whole test suite.

**Comment by jason0x43** [comment]
The issue was actually negative object length (e.g., `obj.index = -1`); I misspoke earlier. In any case, it does appear to be confined to the older versions of FF I was testing. Newer FF, IE, and Chrome are fine.
