### ISSUE TITLE
Accessibility (a11y)

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#177]
We need to define our approach to accessibility.  There are several considerations.

_TODO: Flesh this out before Monday_

**Comment by dylans** [comment]
@kitsonk does this belong in core or should this be in meta?

**Comment by kitsonk** [comment]
Issue moved to [dojo/meta #82](https://github.com/dojo/meta/issues/82) via [**ZenHub**](https://www.zenhub.com/)
