### ISSUE TITLE
Importing 'request' from 'main' in TS fails

### ISSUE THREAD

**Issue by sebilasse** [dojo/core#179]
When I 
`import { request, lang } from '../../core/src/main';`
then
`request` is `undefined`

my workaround - In main.ts :
When I change
`import request from './request';`
to
`import * as request from './request';`
it works.

The underlying issue seems to be in Task.ts since it is referencing the Promise from dojo-shim.

**Comment by kitsonk** [comment]
What type of loader are you using?

When you saying you `import { request, lan } from '../../core/src/main';` I assume you mean in some sort of module.  Why are you importing it relatively?

> The underlying issue seems to be in Task.ts since it is referencing the Promise from dojo-shim.

I am unclear how you think this relates to the issue described above.

**Comment by sebilasse** [comment]
I am importing it native in TS in a module that compiles to UMD.
Relatively because even if shim and core are on the same level they can't reference each other...
I get errors that core can't find has from shim and so on.
I guess I need baseUrl, coming in TS 2.0 ?
http://stackoverflow.com/questions/35065880/typescript-declare-module (1st answer)
The 2nd answer says it is looking in package.json but I tried to install dojo-core npm --save and that did not work either.

**Comment by kitsonk** [comment]
> I am importing it native in TS in a module that compiles to UMD.

Yes, but what loader are you using for the compiled TypeScript?  It is sounding like you are using the CJS loader as part of Node.js.  If you aren't using an AMD loader, you are running into issue #166 and should try to `import { request } from 'dojo-core';`, though that causes other issues potentially.  For now, we can only support an AMD loader with Dojo 2 until we can better figure out how to support a module loader that does not allow rebasing of packages.

> I guess I need baseUrl, coming in TS 2.0 ?

That will help with the type acquisition, but does nothing to help a non-rebaseable loader (like the CJS one with Node.js) work.

**Comment by kitsonk** [comment]
The format of public packages should now be aligned better to situations when using with an AMD loader or a CommonJS loader (e.g. NodeJS).  We have also migrated to UMD definition files in these packages, which solves some type acquisition issues.  So this use case should be solved now.
