### ISSUE TITLE
Migrate from Task to cancellable Promise

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#183]
There is now a Stage 1 Proposal to [add cancelability to `Promise`](https://docs.google.com/presentation/d/1V4vmC54gJkwAss1nfEt9ywc-QOVOfleRxD5qtpMpc8U/edit#slide=id.gc6f9e470d_0_0).

We already adjust the native ES6 Promise a bit in `core`, but we could also adopt the functionality described in the proposal and hope that we can offload this in the future.

This means that `Task` could be removed and code refactored to use the functionally enhanced `Promise`.

**Comment by novemberborn** [comment]
The proposal adds new syntax so additional support from the TypeScript compiler may be required.

**Comment by kitsonk** [comment]
Issue moved to [dojo/shim #16](https://github.com/dojo/shim/issues/16) via [**ZenHub**](https://www.zenhub.com/)
