### ISSUE TITLE
Deprecated attempt to access property 'changedTouches' on a non-TouchEvent object iOS 10

### ISSUE THREAD

**Issue by Bedrovelsen** [dojo/core#195]
Since iOS 10 customers have reported freezing / slow behaviour on their iOS devices. I dug into what the cause might be and noticed that on desktop safari things seem to run smoothly but on iOS in safari after page is loaded this error is generated on any tap or touch and scroll interaction on a page.
<img width="1280" alt="screen shot 2016-09-21 at 1 11 17 pm" src="https://cloud.githubusercontent.com/assets/868085/18892722/df76e26a-84c7-11e6-915e-aa7169ed6981.png">

dojo.js:8037Deprecated attempt to access property 'changedTouches' on a non-TouchEvent object.

Attachment shows results after scrolling up and down a page  a few times causes about 100 errors quickly and the freezing starts when the errors get to a certain point.

Any ideas as to what changed that would cause such an issue?

**Comment by dylans** [comment]
Hi @Bedrovelsen this is the repo for Dojo 2, so not really in the right place. You should either file a bug at http://bugs.dojotoolkit.org/ or ask on the mailing list, see https://dojotoolkit.org/community/ for more information. Thanks

**Comment by Bedrovelsen** [comment]
Thanks, I have now done so.
