### ISSUE TITLE
dojo-core/load and alignment for ES import()

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#202]
There is a Stage 2 proposal for [`import()`](https://github.com/domenic/proposal-import-function) which would essentially be the same as our `load`.

We should potentially consider aligning to that proposal and potentially migrating it to `dojo-shim`.

**Comment by dylans** [comment]
Now at stage 3, we should decide what to do with this.

**Comment by dylans** [comment]
Issue moved to [dojo/meta #133](https://github.com/dojo/meta/issues/133) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dylans** [comment]
Per @matt-gadd : I don't believe we can implement imports here in dojo/core. Mainly due to us needing a contextual require to work with relative paths for AMD. The imports topic is probably a larger discussion in dojo/meta and dojo/loader.
