### ISSUE TITLE
Ability to generate UUID v4

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#214]
We should have the ability to generate UUIDs that are [RFC 4122 v4 compliant](https://www.ietf.org/rfc/rfc4122.txt) as part of core.  This would resolve both dojo/examples#71 and dojo/stores#16.

**Comment by kitsonk** [comment]
Here is [reference to a v4 complaint UUID](https://github.com/kitsonk/hokan/blob/master/util/main.js).

**Comment by kitsonk** [comment]
@agubler suggested we consider node-uuid... I am not sure which is the best long term solution to have common external dependencies

**Comment by rorticus** [comment]
Fixed in https://github.com/dojo/core/pull/244
