### ISSUE TITLE
Proposal: OrderedMap

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#218]
This concept essentially combines the concept of a `Map` plus a `List`/`Array` in that as the keys are added, their order is preserved, as well as potentially APIs to allow you to interact with the collection with array extras.

See #217 for some additional information about the "non-standard" collections we should consider adding to core.

**Comment by rorticus** [comment]
Putting on hold because ES `Map` preserves entry order, and there are currently no requests for array extra extensions to be added. WIP in https://github.com/rorticus/core/tree/issue-218 if we ever decide to pick this up again.

**Comment by kitsonk** [comment]
We don't have a compelling use case.  Closing, until we have one...
