### ISSUE TITLE
Issues with load and loading dojo-shim/Promise

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#228]
When `dojo-shim/Promise` has not been loaded before, it cannot be required in the format of `require('dojo-shim/Promise')`.

This does not fail in the tests because they end up loading loading `dojo-shim/Promise` in other ways, so it is available in the loader cache when `require('dojo-shim/Promise')` is called, therefore it is returned.

**Comment by rishson** [comment]
@kitsonk work still needed or OK to close?

**Comment by kitsonk** [comment]
It is likely still an issue.  Someone should look into it.  It was related to #224 and `load` and could easily be masked by the way we test.

**Comment by kitsonk** [comment]
Between changes to shim and the support of ES Import in TypeScript, this issue isn't worth addressing and we need to deprecate `load()`.
