### ISSUE TITLE
TypeScript 2.1: Use of super and this

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#238]
Because of the new transformation based emitter, ES6 code that used to incorrectly compile to ES5 and "work" is now broken in an ES6 emit and the ES5 emit.  Basically, it has to do with the availability of `this` when passing a function to `super()` in a class.  This effects the "unwrapping" of promises when subclassing (like our ExtensiblePromise and Task).  The issue [Microsoft/TypeScript#8060](https://github.com/Microsoft/TypeScript/issues/8060) describes it.

**Comment by taoqf** [comment]
`module + function + Data` with no classes will do very perfectly.

**Comment by dylans** [comment]
Already resolved and in use where relevant.
