### ISSUE TITLE
global events / dojo/topic replacement ? 

### ISSUE THREAD

**Issue by xblox** [dojo/core#258]
hi,
sorry for posting here a regular question.

might it be possible already to rebuild the old dojo/ topic "publish/subscribe" functionality with the new dojo/core/on|Evented classes? I don't need really a detailed answer but just a hint whether its possible or not. I tried a few hours already but didn't make much progress.

At the end I want a mixin which utilizes the new dojo-2 functions and provide 2 functions: subscribe and publish (see below). Having global events (ditched to document, node's "global" or a custom application context-object ) is essential throughout all my applications and I am trying to rewrite this best as possible in TS. 

```ts
interface IEventedMixin {
    /**
     * @param  {string} type Event type
     * @param  {EventCallback} handler The callback function. TODO: support this.method by function or string(method name) !
     * @param  {EventTarget} target? Override handler scope, defaults to this!
     * @returns Handle
     */
    subscribe(type: string, handler: EventCallback, target?: EventTarget): Handle;
    /**
     * @param  {string} type Event type
     * @param  {EventObject} args Event object
     * @returns Array All listeners results
     */
    publish(type: string, args: EventObject): Array<any>;
    
    /////////////////////////////////////////////////////////////
    // lifecycle    
    _destroyHandles(type?:string);
    
    /////////////////////////////////////////////////////////////
    // sweats
    /**
     * Unregister from a global event.
     * @param  {} type
     * @param  {EventCallback|null} handle? If null: unsubscribe all handlers, otherwise only the specific one
     * @returns boolean
     */
    off(type, handler: EventCallback | null): boolean;
    /**
     * Return listeners per event type
     * @param  {string} type
     * @returns Array
     */
    listener(type: string): Array<EventCallback>;

    ////////////////////////////////////////////////////////////
    // properties
    /**
     * @TODO: 
     * - where did dojo/topic registered the event listeners? : looks like document
     * - figure out a way to use top level objects like "ApplicationContext" intead
     * - support delegation to something else
     */
    scope: HTMLElement | EventEmitter | EventTarget;

    //our collected handles per event type
    __events:EventHandlesPerType;
}

interface EventHandlesPerType{    
    type:string;
    handlers:Array<EventCallback>
}

```

**Comment by xblox** [comment]
never, mind. 
i moved for now to https://github.com/rogierschouten/ts-events (worth it to look at).

**Comment by dylans** [comment]
I'm reopening this as we should still consider your request, which is global publish/subscribe, or what other pattern should be used, or if ts-events is the answer.

**Comment by kitsonk** [comment]
Yes, we should consider the request, but essentially it is a duplicate.  We are going to address those other issues in the near future from a design perspective.

Duplicate dojo/meta#75
Duplicate dojo/meta#142
