### ISSUE TITLE
Implement has loader plugin

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/core#27]
`dojo-core/has` has been implemented, but the loader plugin APIs have not been implemented to allow it to be used for conditionally loading module dependencies.

Conditionally-loaded dependencies look like the following:
- `dojo-core/has!feature?featureModule:noFeatureModule` to load `featureModule` if `feature` is truthy, otherwise load `noFeatureModule`
- `dojo-core/has!feature?featureModule` to load `featureModule` if `feature` is truthy, otherwise load nothing
- `dojo-core/has!feature?:noFeatureModule` to load `noFeatureModule` if `feature` is falsy, otherwise load nothing

We aren't sure yet how much the loader plugin API may deviate from the current AMD plugin API, so implementing this needs to wait until that is settled.  (Or it could initially be developed as a test for whatever new API is taking shape.)

**Comment by bryanforbes** [comment]
As per dojo/loader#9, the loader will stick with the AMD plugin API. The `has` module needs to be updated to add this.

**Comment by kfranqueiro** [comment]
It has occurred to me (after seeing additional comments on dojo/loader#9) that dynamic module loading in general is likely to be a royal pain in the rear-end, whether `has` is implemented as a plugin or not.  Maybe not as unfathomable as the dynamic loading going on in `request` right now, for example, but still not exactly painless to write.  I'm/we're going to have to think about how this is going to end up presenting to end-users.

**Comment by kitsonk** [comment]
Yes, but it is a very powerful feature and it needs to be thought about in the full end-to-end tool chain too.  While expressing conditional loading at the module level is necessary, it should seldom be conditional at final run-time as to deliver efficient code, it should be built out at concatenation/build.

(I think) what we like about AMD, which is less the "asynchronous" but the more robust modularisation than was available in CommonJS and what has been delivered in ES6, but modularisation that allowed emitting concise optimised layers.  AMD, has and the build tool in Dojo 1 was pretty "feature complete" though, ironcially, the ability for it all to work functionally the same without the build step let a lot of end-developers to never build optimised and led a level of criticism that Dojo 1 was "slow".

**Comment by kfranqueiro** [comment]
Yeah, that's a good point, either way we will also need to accommodate resolving this stuff at build time like Dojo 1 does.

@bryanforbes suggested we should be able to hide _most_ of the dynamic-loading complexity behind an API with something like this (essentially reduced from the stuff in `request`):

``` js
function getDeps(deps) {
    if (typeof define === 'function' && define.amd) {
        return new Promise(function (resolve) {
            require(deps, resolve);
        });
    }
    else if (has('node')) {
        return Promise.resolve(deps.map(function (dep) {
            return require(dep);
        });
    }
    else {
        return Promise.reject(new Error('unknown loader'));
    }
}
```

For the sake of being able to easily call out and resolve feature-conditional deps at build time, we probably still want to expose an explicit API to use, whether it's an AMD plugin or not.  Totally off-the-cuff, something like `has.loadFeatureDependency('feature', 'midIfTruthy', 'midIfFalsy')` (which would return a promise).

Users would need to explicitly provide typing information for what this returns, and ideally both modules would adhere to the same interface.  I'm going to poke around at some point to see what kind of use cases we currently have for `has!` in Dojo 1 to see if anything sticks out as presenting a hard time for this.

**Comment by kfranqueiro** [comment]
Another case that currently employs the has plugin in Dojo 1 is the [LocalDB module](https://github.com/SitePen/dstore/blob/v1.1.0/LocalDB.js) in dstore.

Finagling around this a la dojo-core/request and crypto might not be entirely possible, given that some dstore APIs (namely `getIdentity`) are generally never expected to return promises, and having to wait for a promise to resolve just to get the constructor to begin with would be pretty annoying.  So I'm not sure we'd be able to avoid using the plugin in this case.  Granted, it's less of a big deal since this store impl only makes sense in the browser.

**Comment by tomdye** [comment]
Getting involved, planning to pull down @jdonaghue 's branch and adjust with latest updates etc...
