### ISSUE TITLE
Add upload progress reporting

### ISSUE THREAD

**Issue by rorticus** [dojo/core#285]
Once  https://github.com/dojo/core/pull/261 lands, we should add upload progress reporting to the xhr and node providers. Currently, they only provide reporting on download progress.

**Comment by kitsonk** [comment]
Sorry for potentially changing tact on this, but is modelling on events the right paradigm?  This seems like a perfect use case for [`Observable`](https://github.com/dojo/shim/blob/master/src/Observable.ts).  Even the name of the proposed PR seems to indicate that is the right paradigm. 😁
