### ISSUE TITLE
Typings Bundle does not include the whole library...

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#3]
When I use:

``` sh
grunt dist
```

I get `dist/typings/dojo-core/dojo-core-2.0.0.d.ts` output and it includes all the modules in the root of `src`, but not the modules in the sub directories `src`.  For example, the file has:

``` ts
import ObjectObserver from 'dojo-core/observers/ObjectObserver';
```

but does not have a corresponding `declare module 'dojo-core/observers/ObjectObserver'`.

While this comes back as a valid file within the repository, when copying `dist` to another repository, it generates several TypeScript errors about not being able to resolve the modules.

I don't know if this is a `dts-generator` issue, or something to do with the configuration of it within `core`.

**Comment by bryanforbes** [comment]
I committed a change (fd2df9157cc1eb73c9859ac28a19dc65b3772c17) that fixes the exported interfaces so the typings are correctly generated. There's also a [pull request for dts-generator](https://github.com/SitePen/dts-generator/pull/18) which will throw an error when the situation you're seeing arises within the code. Should we keep this open until a new version of dts-generator is released with the fix?

**Comment by kitsonk** [comment]
Well, I can confirm it resolves the specific issue I reported. Technically
the change to dts-generator is an improvement. So I say close.

**Comment by kitsonk** [comment]
This appears to be resolved.
