### ISSUE TITLE
Invalid URL for blob has sniff

### ISSUE THREAD

**Issue by agubler** [dojo/core#318]
**Bug** 

The URI of `/` is not valid for the blob sniff in `has.ts`, which causes a failure running tests for projects built with webpack.

This should be updated to `/foo` (or another valid URI)

**Comment by msssk** [comment]
This should use an absolute URI, see https://github.com/dojo/dojo/pull/260

**Comment by agubler** [comment]
@msssk I did see that fix afterwards as @Dylans posted in dojo2, this is to make it work in web workers?

**Comment by agubler** [comment]
@msssk please can you open a new issue to update this for web workers?

**Comment by msssk** [comment]
@agubler Done: #320
