### ISSUE TITLE
Move `widget/keys` module to `core`?

### ISSUE THREAD

**Issue by msssk** [dojo/core#322]
**Enhancement**

Should `dojo/core` include a `keys` module similar to Dojo 1's [`dojo/keys`](https://github.com/dojo/dojo/blob/master/keys.js)?

The Dojo 2 ecosystem would definitely benefit from such a module, but there's some question of which package it should be in.

Providing it in `dojo/core` makes it available to all Dojo-based development, including non-widget UIs and cli apps.

The [`KeyboardEvent.key`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) property is widely supported - we should match it and follow the [W3 spec](https://www.w3.org/TR/DOM-Level-3-Events-key/#key-value-tables) for `key` values.

**Comment by kitsonk** [comment]
I am afraid at this point we need to mature our user input and handling.  Right now I don't think it makes sense to migrate it into core, but we can re-evaluate in the future if required.  Closing for now.
