### ISSUE TITLE
Move Evented interfaces and types from `dojo/interfaces` to `Evented.ts`

### ISSUE THREAD

**Issue by agubler** [dojo/core#334]
**Enhancement**

The interfaces and types related to `Evented.ts` should be moved from the `@dojo/interfaces` package into the `Evented.ts` module as there is little benefit to them being in a separate package. In fact it adds overhead when making changes to the `Evented` functionality.

**Comment by kitsonk** [comment]
Since this is ultimately a "nice to have" I have moved it to the RC, but if we can pick it up at some point ahead of that 😁

**Comment by agubler** [comment]
This will be achieved when https://github.com/dojo/meta/issues/223 is completed.

**Comment by dylans** [comment]
Resolved.
