### ISSUE TITLE
request interfaces body is missing upload

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#340]
**Bug** 

[`src/request/interfaces::Body`](https://github.com/dojo/core/blob/master/src/request/interfaces.d.ts#L6) is missing `upload()` though this is specified as a required abstract body on the `Response` class.

**Comment by rorticus** [comment]
Not finding anything, had @kitsonk try to reproduce and its working now for him too. I think this probably got fixed with the final version of the upload code.
