### ISSUE TITLE
Add API to dynamically load modules

### ISSUE THREAD

**Issue by bryanforbes** [dojo/core#35]
Because ES6 module imports can only be used at the top-level of a module (they cannot be used inside of a block) and because Node's loader does not understand AMD loader plugins, it would be good to have an API for dynamically loading modules. The API should take a variable number of module IDs and return a promise that fulfills with an array of the module values. At this time, I think this should go into its own module and be called `require`. The implementation could be as simple as the following:

``` ts
import Promise from './Promise';

declare var require: Function;

const _require: {
    (...moduleIds: string[]): Promise<any[]>;
} = (function () {
    if (typeof define === 'function' && define.amd) {
        return function (...moduleIds: string): Promise<any[]> {
            return new Promise(function (resolve, reject) {
                // TODO: hook up reject
                require(moduleIds, resolve);
            });
        };
    }
    else if (has('host-node')) {
        return function (...moduleIds: string): Promise<any[]> {
            return Promise.resolve(moduleIds.map(function (moduleId) {
                return require(moduleId);
            }));
        };
    }
    return function () {
        return Promise.reject(new Error('Unknown loader'));
    };
})();
export { _require as default };
```

Once we have this, the code at https://github.com/dojo/core/blob/master/src/request.ts#L69-L82 can be removed for a `dojo-core/require` call. In addition, the observers pulled in in `observe.ts` could be done this way as well as any of the providers in crypto and bundles in i18n.

**Comment by msssk** [comment]
Is `require` really a good module name, considering the loader defines a global `require` function? And Node passes a `require` function to everything.

**Comment by kitsonk** [comment]
I don't see any problems with `require`... there are lots of things we name that conflict with items in the global namespace or are properties of other objects.  As long as it isn't a reserved word in ES or TS...

As far as another consideration for this, consideration should also be given for build optimisation of these dynamically required modules.

Another use case is (potentially) dynamic module loading in the parser (again an end developer design friendly feature which should be build optimised).

**Comment by bryanforbes** [comment]
That's a good question, so I tested it out. Given this module:

``` ts
import Promise from './Promise';

export interface Require {
    (...moduleIds: string[]): Promise<any[]>;
}

const _require: Require = (function (): any {
    return function () {
        return Promise.reject(new Error('Unknown loader'));
    };
})();
export default _require;
```

The following JS is emitted by our build process:

``` js
(/* istanbul ignore next */ function (deps, factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(deps, factory);
    }
})(["require", "exports", './Promise'], function (require, exports) {
    var Promise_1 = require('./Promise');
    var _require = (function () {
        return function () {
            return Promise_1.default.reject(new Error('Unknown loader'));
        };
    })();
    exports.default = _require;
});
//# sourceMappingURL=require.js.map
```

A module using it would look like this:

``` ts
// foo.ts
import require from './require';

require('bar').then(function ([ bar ]) {
    bar();
});
```

And the emitted JS from our build process is:

``` js
(/* istanbul ignore next */ function (deps, factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(deps, factory);
    }
})(["require", "exports", './require'], function (require, exports) {
    var require_1 = require('./require');
    require_1.default('bar').then(function (_a) {
        var bar = _a[0];
        bar();
    });
});
//# sourceMappingURL=foo.js.map
```

Even thought the name won't conflict with node or AMD's `require`, I agree that `require` might be confusing, so I'm open to other name suggestions. While writing this up I thought about `loadModules`, `getModules`, and a few others, but I didn't really like them.

**Comment by kitsonk** [comment]
Is there anything wrong with just `load`?

**Comment by bryanforbes** [comment]
I didn't want it to get confused with the AMD plugin API. If you don't think that's a concern, then `load` is fine.

**Comment by kfranqueiro** [comment]
I'd be far less concerned about people confusing `load` (especially from a consumer perspective) than `require`, and was considering that name myself.  Or `loadModule`.  Or with an `s`, like you said, because I can't read and forgot this can load any number of them at once.

**Comment by kitsonk** [comment]
I would still feel all [Bauhaus](https://en.wikipedia.org/wiki/Bauhaus) and use `load`, especially if it becomes the way to load other resources too (like JSON, text, etc...).
