### ISSUE TITLE
old dojox.storage documentation is broken

### ISSUE THREAD

**Issue by spaceone** [dojo/core#355]
https://dojotoolkit.org/reference-guide/1.10/dojox/storage.html says to use the deprecated:
dojo.addOnLoad() and the example aren't even working. It seems dojo.addOnLoad is never called.

Could you upgrade the documentation to reflect an modern state?
At least say a word that https://github.com/SitePen/dstore/blob/master/docs/Stores.md could be used instead? Or how to use dojox/storage/LocalStorageProvider as an  AMD module?

**Comment by dylans** [comment]
Note that this repo is for Dojo 2... so I'm going to move this issue to the dojo/docs repo where we'd be happy to accept a pull request to get this landed.

**Comment by dylans** [comment]
Issue moved to [dojo/docs #154](https://github.com/dojo/docs/issues/154) via [**ZenHub**](https://www.zenhub.com/)
