### ISSUE TITLE
 I just would like to use dojo2 as a library, it looks a little complex, how could I use it like a react or dojo1?

### ISSUE THREAD

**Issue by renyaoxiang** [dojo/core#371]
I would like to use it as a library. I did not find a guide or tutorial.
Pleasure to have your some suggestion.

**Comment by kitsonk** [comment]
The tutorials are located at [dojo.io/tutorials](https://dojo.io/tutorials).

Is there anything missing there you would expect to help you get started?

**Comment by kitsonk** [comment]
Question answered, closing.

**Comment by renyaoxiang** [comment]
@kitsonk 
Thank you any way.

**Comment by kitsonk** [comment]
@renyaoxiang did the link to the tutorials not help you?

**Comment by renyaoxiang** [comment]
Dear @kitsonk 
Not all. In my case, I would like to use dojo2 sometimes together with react, I found it a bit heavy as said in the tutorials, as it seems that I have to install @dojo/cli. 
Also I could understand not at all about the @theme in dojo2, while I would like to have a separate less file to gather all styles by browerify, not by webpack, it may occur a error and I have no way I think.

**Comment by dylans** [comment]
Re-opened as @renyaoxiang does not feel the question was answered.

**Comment by bitranch** [comment]
First, you don't need `@dojo/cli` to use dojo2. We use dojo2 in a tool chain that doesn't make use of any of the `cli` functionality. Based on our experience, `@dojo/cli` is there to help you get started (and supply a tool chain), but it's not any kind of requirement. If you pull the dojo2 packages from npm, you can use them pretty much as you'd use any other js package.

As for using dojo2, I've found it a lot simpler to include "as a library" than dojo1. We use webpack, so there may be complexities with using it in browserify, but I'd be surprised if dojo2 wasn't still easier to set up and use.

By the way, I'm a dojo2 user and not a committer.

**Comment by renyaoxiang** [comment]
Dear @bitranch 
Thank you very much, now I have no puzzlement.

**Comment by agubler** [comment]
Thank you @bitranch
