### ISSUE TITLE
Why do we have our own interface EventEmitter in on.ts?

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/core#38]
Given that we use `node.d.ts` elsewhere, should we simply be using its `NodeJS.EventEmitter` interface, or is there a reason for us exposing a minimal subset here (and relying on it elsewhere e.g. streams)?

**Comment by bryanforbes** [comment]
The node EventEmitter interface is becoming more common (even on the front-end) and I don't want to require users that aren't using node to have to include all of `node.d.ts` for a simple interface.

**Comment by kfranqueiro** [comment]
Given what @bryanforbes said, and the realization that leaning on `NodeJS.EventEmitter` would likely cause the entirety of `node.d.ts` to end up in our own generated `d.ts`, I'm going to close this and leave the code as-is.
