### ISSUE TITLE
has.ts causes loading the main bundle to crash in Internet Explorer 11 in https

### ISSUE THREAD

**Issue by szwoelf** [dojo/core#387]
**Bug**

When using a bundled application with Internet Explorer 11 together with `https` the bundle is not loaded. IE raises an "access denied" error in the main bundle. 

Package Version: dojo RC1 (and RC2)

**Code**

can be tested with:
* create a fresh app with dojo/cli
* add the following code after the imports:

`
import request from '@dojo/core/request';
console.log(request);
`

* pack the application with `dojo build -m dist`
* access the application via https://localhost:... in IE 11

**Actual behavior:**

IE 11 will not show the rotating elements - it will show an error in the console (no SVG, ... )

**Comment by szwoelf** [comment]
Internet Explorer seems to have a problem with the request to http://www.google.com .... (see line 22 in has.ts) ....

**Comment by dasa** [comment]
Maybe it should be using `https`, like it does here in Dojo 1: https://github.com/dojo/dojo/blob/master/request/xhr.js#L40

**Comment by szwoelf** [comment]
Hi ... yes. I patched this in the `has.js` in the node_modules, performed a build and re-tested this in IE. Using the URL `https://www.google.com` works. Possibly the comment of the code mentioned by @dasa should also be added ...

**Comment by agubler** [comment]
@szwoelf do you fancy raising a pull request to fix this?
