### ISSUE TITLE
Support the abortable fetch API

### ISSUE THREAD

**Issue by dasa** [dojo/core#390]
**Enhancement**

Add support for a `signal: AbortSignal` property to `RequestOptions`

Package Version: 2.x

**Code**

This would allow `core/request` to support the [Abortable fetch](https://developers.google.com/web/updates/2017/09/abortable-fetch) pattern.

There'd need to be a shim for `AbortController` too.

**Comment by nicknisi** [comment]
@dasa This fix has been merged into @dojo/framework via dojo/framework#30 and will be included in Dojo 3. Thanks!
