### ISSUE TITLE
dojo/widget-core typo in code snippet

### ISSUE THREAD

**Issue by sombrerox** [dojo/core#397]
There is a minor typo in one of the code snippets in _dojo/widget-core/documentation_, there is a following code snippet there: 

`interface ListProperties {
    items: {
        id: string;
        content: string;
        highlighted: boolean;
    };
}

class List extends WidgetBase<ListProperties> {
    protected render() {
        const { items } = this.properties;

        return v('ul', { classes: 'list' }, items.map((item) => {
            const { id, highlighted, content } = item;
            const classes = [ highlighted ? 'highlighted' : null ];

            return v('li', { key: id, classes }, [ content ]);
        });
    }
}`

map() is being used on an object, I believe author wanted to define _items_ property as an **array** of

 _{
        id: string;
        content: string;
        highlighted: boolean;
 }_

like:

 _{
        id: string;
        content: string;
        highlighted: boolean;
 }[]_

rather than a single instance.

This is my first time posting so forgive me for bad formatting, I'm having some problems with code tag. 
I have seen more minor mistakes in code elsewhere in documentation, I'll make sure to post back when/if I stumble upon them.

**Comment by agubler** [comment]
Issue moved to [dojo/widget-core #957](https://github.com/dojo/widget-core/issues/957) via [**ZenHub**](https://www.zenhub.com/)
