### ISSUE TITLE
Proposal: use strict

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#4]
Shouldn't we be adopting `'use strict';` in all modules (except for `global.ts`)?  It enables the environment to perform optimisations that are still quite significant.  While IE9 does not support strict mode, all the other supported environments do.

**Comment by csnover** [comment]
What quite significant optimisations does 'use strict' enable?

**Comment by kitsonk** [comment]
Ok, I retract my previous statement.  It was a misunderstanding of the implications of:

> JavaScript in browsers can access the user's private information, so such JavaScript must be partially transformed before it is run, to censor access to forbidden functionality. JavaScript's flexibility makes it effectively impossible to do this without many runtime checks. Certain language functions are so pervasive that performing runtime checks has considerable performance cost. A few strict mode tweaks, plus requiring that user-submitted JavaScript be strict mode code and that it be invoked in a certain manner, substantially reduce the need for those runtime checks.

From [MDN on Use Strict](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode).  It obviously applies to code which you are attempting to run securely (e.g. JSFiddle), since the JIT can't fully optimise it.

I tried to find some further evidence, because logically it still makes sense that certain things would be slightly more performance, because the JIT would have less options (and at the very least `arguments.callee` is removed).  Then I read it can actually slowdown `Array.prototype.slice.call(arguments)` because the JIT cannot detect that it is a special type of array in strict mode, though the [results](https://jsperf.com/use-strict-arguments) seem to be mixed for me.

So at best it would be performance improvement likely negligible and with sufficient checking in TypeScript, the strictness underneath could be considered redundant.
