### ISSUE TITLE
`request` should append query/cache-bust strings to the end of the URL.

### ISSUE THREAD

**Issue by mwistrand** [dojo/core#49]
Currently passing in a query string/object or specifying `cacheBust: true` has no effect.

**Comment by mwistrand** [comment]
(I am working on a fix to this; at this point I just need to update the tests.)

**Comment by kfranqueiro** [comment]
Bear in mind that https://github.com/dojo/core/pull/48 was submitted yesterday, so if you'd like to leave @maier49 a note as to how to test it, perhaps he could add the test there.
