### ISSUE TITLE
WHATWG Streams

### ISSUE THREAD

**Issue by dylans** [dojo/core#90]
It looks like the WHATWG spec has had a fair amount of churn, based on this comment: "Although readable streams have been significantly evolved recently due to implementation progress providing feedback, writable streams have not yet caught up to all the discoveries in that space. As such, while the following spec will be the basis for a final API, it is expected to change in several important ways before being ready to ship. Please follow along on the writable streams issues label for details. "

I think we should probably review the changes to the spec since our implementation was last touched 5-7 months ago.

**Comment by nicknisi** [comment]
FWIW, I believe that part about writable streams was there when we originally created this implementation. However, I believe a lot has still changed.

**Comment by bitpshr** [comment]
The [writable streams label](https://github.com/whatwg/streams/issues?q=label%3A%22writable+streams%22+is%3Aclosed) for the WHATWG streams specification doesn't show any major changes via closed issues. After chatting with @nicknisi briefly about an approach to this one, I'm going to go back through the spec itself to make sure everything is still covered using [this diff](https://github.com/whatwg/streams/compare/9653b07349db123f02038eee6a555719dc866ca0...master) as a basis (thanks, Nick!)

This manual approach may take some time, though, so any other suggestions to easily identify spec changes (for this spec or any others going forward) would be helpful.

**Comment by bitpshr** [comment]
I've been working to update our implementation to match the current spec [here](https://github.com/dojo/core/compare/master...bitpshr:issue-90-streams?expand=1). It's slow progress; I've been focusing on API changes first and foremost, and I port over test changes, additions, and deletions where applicable. Ultimately, we'll need to write a test suite that fully hammers the spec, because the WHATWG tests are pretty limited and specific to their implementation.

For posterity,[ this diff](https://github.com/whatwg/streams/compare/8dca04e41804e70240ce050874238fa828f47fcb...master) shows the remaining commits we need to go through to get our implementation up to date.

**Comment by bitpshr** [comment]
I went through 50 more commits, updating our streams implementation to match the current spec. Current progress can be found [here](https://github.com/dojo/core/compare/master...bitpshr:issue-90-streams?expand=1).

[This diff](https://github.com/whatwg/streams/compare/e601d69f3ba40e6f4b5506e4bb1fbe3f3eabf393...master) now shows what's left. There's only 25 commits remaining, but the next one to dig through involves merging ReadableByteStream and ReadableStream, so it's essentially a rewrite of the latter. Did we ever decide that streams were a definite for Dojo 2? @kitsonk @dylans

**Comment by kitsonk** [comment]
We should consider breaking out stream from `dojo-core`.  For what we thought we might use streams for in Dojo 2 has largely been supplanted by ES Observables.  Therefore I think it should be migrated to its own package and removed from `core`, though there is a bit of intertwining with `request`.

**Comment by dylans** [comment]
To add to this, core/request/node depends on streams. It does not look trivial to decouple request/node's usage of streams (e.g. into a version that doesn't rely on streams, with streams perhaps extending the capabilities of the request when included.

So it may make sense to move request/node into the streams package, or put both into a core-server or core-node package, though streams may have a use client-side, so I don't really know what the right answer is, but it's not easy to unwind at this point (which was the main reason they were included in one package early on as they were originally separate).

If we can decide on how we should restructure things, I would be open to doing the refactoring work unless someone else wants to tackle it.

**Comment by kitsonk** [comment]
It is in there, but the architecture of `core/request` allows registration of additional handlers... the default `core/reuest/node` currently uses it, but it is an arbitrary usage versus a hard dependency.

**Comment by dylans** [comment]
When #225 is finished, move this issue into new dojo/streams package.

**Comment by dylans** [comment]
Issue moved to [dojo/streams #2](https://github.com/dojo/streams/issues/2) via [**ZenHub**](https://www.zenhub.com/)
